name: Gerar APK SAMP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 8 (O mais compatível)
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Permissão
        run: chmod +x gradlew

      - name: Compilar APK (Forçar build)
        # O pulo do gato: ignorar erros de lint e metadados que travam o SAMP
        run: |
          ./gradlew assembleDebug \
          -x lint \
          -x test \
          -Dorg.gradle.daemon=false \
          -Dorg.gradle.parallel=false \
          --stacktrace

      - name: Upload do APK
        if: always() # Tenta fazer o upload mesmo se der algum aviso
        uses: actions/upload-artifact@v4
        with:
          name: samp-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
